info:
  version: 1.0.1
  description: PCF initial local configuration

configuration:
  pcfName: PCF # the name of this PCF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.7 # IP used to register to NRF
    bindingIPv4: 127.0.0.7  # IP used to bind the service
    port: 8000              # port used to bind the service
    tls: # the local path of TLS key
      pem: config/TLS/pcf.pem # PCF TLS Certificate
      key: config/TLS/pcf.key # PCF TLS Private key
  timeFormat: 2019-01-02 15:04:05 # time format of this PCF
  defaultBdtRefId: BdtPolicyId-   # BDT Reference ID, indicating transfer policies of background data transfer.
  nrfUri: http://127.0.0.10:8000  # a valid URI of NRF
  serviceList:   # the SBI services provided by this PCF, refer to TS 29.507
    - serviceName: npcf-am-policy-control # Npcf_AMPolicyControl service
    - serviceName: npcf-smpolicycontrol   # Npcf_SMPolicyControl service
      suppFeat: 3fff # the features supported by Npcf_SMPolicyControl, name defined in TS 29.512 5.8-1, value defined in TS 29.571 5.2.2
    - serviceName: npcf-bdtpolicycontrol    # Npcf_BDTPolicyControl service
    - serviceName: npcf-policyauthorization # Npcf_PolicyAuthorization service
      suppFeat: 3    # the features supported by Npcf_PolicyAuthorization, name defined in TS 29.514 5.8-1, value defined in TS 29.571 5.2.2
    - serviceName: npcf-eventexposure       # Npcf_EventExposure service
    - serviceName: npcf-ue-policy-control   # Npcf_UEPolicyControl service
  mongodb:       # the mongodb connected by this PCF
    name: free5gc                  # name of the mongodb
    url: mongodb://localhost:27017 # a valid URL of the mongodb
  locality: area1 # Name of the location where a set of AMF, SMF, PCF and UPFs are located

# the kind of log output
# debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
# ReportCaller: enable the caller report or not, value: true or false
logger:
  PCF:
    debugLevel: info
    ReportCaller: false
