info:
  version: 1.0.0
  description: Routing information for UE

ueRoutingInfo:
  - SUPI: imsi-2089300007487
    AN: 10.200.200.101
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2

  - SUPI: imsi-2089300007486
    AN: 10.200.200.102
    PathList:
      - DestinationIP: 10.0.0.10
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 10.0.0.11
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2

routeProfile:
  MEC1:
    forwardingPolicyID: 10

pfdDataForApp:
  - applicationId: edge
    pfds:
      - pfdID: pfd1
        flowDescriptions:
          - permit out ip from 60.60.0.1 8080 to any
