name: My5Gcore Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Checkout Submodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.7
        
      - name: Check Versions
        run: |
          lsb_release -a
          uname -a
          go version
          git --version
          docker --version
          echo "pwd: $(pwd)"
          echo "GOROOT: $GOROOT"
          echo "GOPATH: $GOPATH"
          echo "Listing dirs"
          ls -la
          sudo ln -s $GOROOT /usr/local/go
          
      - name: Install Go Deps
        run: | 
          go mod download
          
      - name: MongoDB
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image_version: latest
          port: 27017
          
      - name: Packages Control Plane
        run: |
          sudo apt -y -q update
          sudo apt -y -q install wget git
          
      - name: Packages User Plane
        run: | 
          sudo apt -y update
          sudo apt -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev
          go get -u github.com/sirupsen/logrus
          
      - name: GTP5G module
        run: | 
          uname -r
          git clone -b master https://github.com/jplobianco/gtp5g.git ./src/upf/build/
          cd src/upf/build
          make
          sudo make install    
          lsmod | grep gtp
              
      - name: Build NFs
        run: sudo make all
          
      - name: TestRegistration
        run: |
          chmod +x test.sh
          ./test.sh TestRegistration
      
      - name: TestGUTIRegistration
        run: ./test.sh TestGUTIRegistration
        
      - name: TestServiceRequest
        run: ./test.sh TestRegistration
      
      - name: TestXnHandover
        run: ./test.sh TestXnHandover
      
      - name: TestN2Handover
        run: ./test.sh TestN2Handover
         
      - name: TestDeregistration
        run: ./test.sh TestDeregistration
         
      - name: TestPDUSessionReleaseRequest
        run: ./test.sh TestPDUSessionReleaseRequest
         
      - name: TestPaging
        run: ./test.sh TestPaging
       
      - name: TestNon3GPP
        run: ./test.sh TestNon3GPP

      - name: TestReSynchronisation
        run: ./test.sh TestReSynchronisation
